### ISSUE TITLE
[MacOS M1] 無法正常開啟各平台

### ISSUE THREAD

**Issue by iita71737** [max32002/tixcraft_bot#139]
```
run button pressed.
save config result: True
execute in shell mode.
try python3
Traceback (most recent call last):
  File "/Users/chihhao/Downloads/MaxBot.app/Contents/Resources/chrome_tixcraft.py", line 46, in <module>
    from PIL import Image
  File "/Users/chihhao/Downloads/MaxBot.app/Contents/Resources/PIL/Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/Users/chihhao/Downloads/MaxBot.app/Contents/Resources/PIL/__init__.py)
```

Termanal出現以上訊息～

**Comment by max32002** [comment]
https://github.com/max32002/tixcraft_bot/commit/88dbe5841c101595ad25005df53c14ddd9ff3131
Please download 2023-11-19.

**Comment by iita71737** [comment]
Thank u , my hero.

**Comment by max32002** [comment]
you are welcome 😺

DanLin ***@***.***> 於 2023年11月25日 週六 上午11:30 寫道：

**Comment by hua1215** [comment]
您好，2023-11-19版本仍然出現以下訊息：

`ImportError: cannot import name '_imaging' from 'PIL'`
