### ISSUE TITLE
遠大，在沒票刷新的情況下，過幾分鐘瀏覽器就會閃退

### ISSUE THREAD

**Issue by eric40325** [max32002/tixcraft_bot#162]
閃退的時候cmd的錯誤訊息如下：
```
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C6276FBD60>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。')': /session/60ad3a05b651d20d6e5e365a2687ff2d/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C6276FA3E0>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。')': /session/60ad3a05b651d20d6e5e365a2687ff2d/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C6276F99F0>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。')': /session/60ad3a05b651d20d6e5e365a2687ff2d/element
WARNING:urllib3.connectionpool:Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C6276FB5B0>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。')': /session/60ad3a05b651d20d6e5e365a2687ff2d/url
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C6276F81F0>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。')': /session/60ad3a05b651d20d6e5e365a2687ff2d/url
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C6276FA140>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。')': /session/60ad3a05b651d20d6e5e365a2687ff2d/url
ERROR:logger:Maxbot URL Exception
ERROR:logger:HTTPConnectionPool(host='localhost', port=60521): Max retries exceeded with url: /session/60ad3a05b651d20d6e5e365a2687ff2d/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C6276FAB90>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。'))
Traceback (most recent call last):
  File "urllib3\connection.py", line 203, in _new_conn
  File "urllib3\util\connection.py", line 85, in create_connection
  File "urllib3\util\connection.py", line 73, in create_connection
ConnectionRefusedError: [WinError 10061] 無法連線，因為目標電腦拒絕連線。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 790, in urlopen
  File "urllib3\connectionpool.py", line 496, in _make_request
  File "urllib3\connection.py", line 395, in request
  File "http\client.py", line 1278, in endheaders
  File "http\client.py", line 1038, in _send_output
  File "http\client.py", line 976, in send
  File "urllib3\connection.py", line 243, in connect
  File "urllib3\connection.py", line 218, in _new_conn
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001C6276FAB90>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chrome_tixcraft.py", line 12159, in get_current_url
  File "undetected_chromedriver\__init__.py", line 639, in __getattribute__
  File "selenium\webdriver\remote\webdriver.py", line 438, in current_url
  File "selenium\webdriver\remote\webdriver.py", line 346, in execute
  File "selenium\webdriver\remote\remote_connection.py", line 300, in execute
  File "selenium\webdriver\remote\remote_connection.py", line 321, in _request
  File "urllib3\_request_methods.py", line 110, in request
  File "urllib3\_request_methods.py", line 143, in request_encode_url
  File "urllib3\poolmanager.py", line 444, in urlopen
  File "urllib3\connectionpool.py", line 874, in urlopen
  File "urllib3\connectionpool.py", line 874, in urlopen
  File "urllib3\connectionpool.py", line 874, in urlopen
  File "urllib3\connectionpool.py", line 844, in urlopen
  File "urllib3\util\retry.py", line 515, in increment
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=60521): Max retries exceeded with url: /session/60ad3a05b651d20d6e5e365a2687ff2d/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001C6276FAB90>: Failed to establish a new connection: [WinError 10061] 無法連線，因為目標電腦拒絕連線。'))
quit bot by error: Max retries exceeded
```

**Comment by max32002** [comment]
解法: MaxBot 自動重啟瀏覽器
https://youtu.be/mp6pYgniaPU

如果可以的話, 電腦不要做其他事情, 並關閉其他程式與防毒軟體, 以增加可以使用的記憶體.
