### ISSUE TITLE
拓元搶票時，遇到需要驗證碼會發生 KeyError 並關閉瀏覽器

### ISSUE THREAD

**Issue by HPJ1996** [max32002/tixcraft_bot#164]
過去版本可能有使用到 `config_dict["advanced"]["online_dictionary_url"]` 參數
近期再改版時忘了修正，導致執行到此行 `get_answer_list_from_user_guess_string`  的 `if len(config_dict["advanced"]["online_dictionary_url"]) > 0:` 會發生錯誤

```
Traceback (most recent call last):
  File "/Users/user/tixcraft_bot/chrome_tixcraft.py", line 12591, in <module>
    cli()
  File "/Users/user/tixcraft_bot/chrome_tixcraft.py", line 12542, in cli
    main(args)
  File "/Users/user/tixcraft_bot/chrome_tixcraft.py", line 12443, in main
    tixcraft_dict = tixcraft_main(driver, url, config_dict, tixcraft_dict, ocr, Captcha_Browser)
  File "/Users/user/tixcraft_bot/chrome_tixcraft.py", line 7731, in tixcraft_main
    tixcraft_dict["fail_list"] = tixcraft_verify(driver, config_dict, tixcraft_dict["fail_list"])
  File "/Users/user/tixcraft_bot/chrome_tixcraft.py", line 3019, in tixcraft_verify
    return tixcraft_input_check_code(driver, config_dict, fail_list, question_selector)
  File "/Users/user/tixcraft_bot/chrome_tixcraft.py", line 3034, in tixcraft_input_check_code
    answer_list = get_answer_list_from_user_guess_string(config_dict)
  File "/Users/user/tixcraft_bot/chrome_tixcraft.py", line 3000, in get_answer_list_from_user_guess_string
    if len(config_dict["advanced"]["online_dictionary_url"]) > 0:
KeyError: 'online_dictionary_url'
```

**Comment by max32002** [comment]
感謝回報, 已修正於2024-01-08 版.
https://github.com/max32002/tixcraft_bot/commit/600433be1ff6ff94f1d1b66968d565118760d2a0
