### ISSUE TITLE
啟動搶票時拋錯

### ISSUE THREAD

**Issue by Cllodh** [max32002/tixcraft_bot#165]
Last login: Wed Jan 17 19:41:06 on ttys000
moore@MBP ~ % cd ~/Downloads/MaxBot.app/Contents/Resources/
moore@MBP Resources % python3 settings.py                          
2024-01-17 19:42:31.224 Python[1269:16776] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
name 'ddddocr' is not defined
server running on port: 16888
setting app version: MaxBot (2024.01.10)
python version: 3.10.11
platform: macOS-14.0-arm64-arm-64bit
run button pressed.
save config result: True
execute in shell mode.
try python3
Traceback (most recent call last):
  File "/Users/moore/Downloads/MaxBot.app/Contents/Resources/chrome_tixcraft.py", line 37, in <module>
    from NonBrowser import NonBrowser
  File "/Users/moore/Downloads/MaxBot.app/Contents/Resources/NonBrowser.py", line 6, in <module>
    from PIL import Image
  File "/Users/moore/Downloads/MaxBot.app/Contents/Resources/PIL/Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/moore/Downloads/MaxBot.app/Contents/Resources/PIL/_imaging.cpython-310-darwin.so, 0x0002): tried: '/Users/moore/Downloads/MaxBot.app/Contents/Resources/PIL/_imaging.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/moore/Downloads/MaxBot.app/Contents/Resources/PIL/_imaging.cpython-310-darwin.so' (no such file), '/Users/moore/Downloads/MaxBot.app/Contents/Resources/PIL/_imaging.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by Cllodh** [comment]
Last login: Wed Jan 17 19:41:06 on ttys000
moore@MBP ~ % cd ~/Downloads/MaxBot.app/Contents/Resources/
moore@MBP Resources % python3 settings.py                          
2024-01-17 19:42:31.224 Python[1269:16776] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
name 'ddddocr' is not defined
server running on port: 16888
setting app version: MaxBot (2024.01.10)
python version: 3.10.11
platform: macOS-14.0-arm64-arm-64bit
run button pressed.
save config result: True
execute in shell mode.
try python3
Traceback (most recent call last):
  File "/Users/moore/Downloads/MaxBot.app/Contents/Resources/chrome_tixcraft.py", line 37, in <module>
    from NonBrowser import NonBrowser
  File "/Users/moore/Downloads/MaxBot.app/Contents/Resources/NonBrowser.py", line 6, in <module>
    from PIL import Image
  File "/Users/moore/Downloads/MaxBot.app/Contents/Resources/PIL/Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/moore/Downloads/MaxBot.app/Contents/Resources/PIL/_imaging.cpython-310-darwin.so, 0x0002): tried: '/Users/moore/Downloads/MaxBot.app/Contents/Resources/PIL/_imaging.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/moore/Downloads/MaxBot.app/Contents/Resources/PIL/_imaging.cpython-310-darwin.so' (no such file), '/Users/moore/Downloads/MaxBot.app/Contents/Resources/PIL/_imaging.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

**Comment by max32002** [comment]
或是直接用 source 來執行:
參看看文章: 如何用虛擬主機搶拓元的門票

https://max-everyday.com/2023/11/buy-ticket-by-vm/

雖然這篇文章是以虛擬主機來示範，但是在 Windows / macOS / Linux 平台裡的 python 操作方式是類似的，幾乎相同。
