### ISSUE TITLE
您好 購買cityline車銀優演唱會門票 為什麼會閃退呢？

### ISSUE THREAD

**Issue by Yul998** [max32002/tixcraft_bot#211]
Traceback (most recent call last):
  File "nodriver_tixcraft.py", line 2332, in <module>
  File "nodriver_tixcraft.py", line 2329, in cli
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "nodriver_tixcraft.py", line 2259, in main
  File "nodriver_tixcraft.py", line 1788, in nodriver_cityline_main
  File "nodriver_tixcraft.py", line 1619, in nodriver_cityline_auto_retry_access
NameError: name 'config_dict' is not defined. Did you mean: 'get_config_dict'?
[28744] Failed to execute script 'nodriver_tixcraft' due to unhandled exception!

**Comment by Yul998** [comment]
進入排隊頁面就會閃退

**Comment by max32002** [comment]
update at 2024-04-02,
https://youtu.be/cLFWyI1BLyw
