### ISSUE TITLE
cityline进入排队界面闪退

### ISSUE THREAD

**Issue by BRKKA7** [max32002/tixcraft_bot#213]
Traceback (most recent call last):
  File "nodriver_tixcraft.py", line 2332, in <module>
  File "nodriver_tixcraft.py", line 2329, in cli
  File "asyncio\base_events.py", line 649, in run_until_complete
  File "nodriver_tixcraft.py", line 2259, in main
  File "nodriver_tixcraft.py", line 1788, in nodriver_cityline_main
  File "nodriver_tixcraft.py", line 1619, in nodriver_cityline_auto_retry_access
NameError: name 'config_dict' is not defined. Did you mean: 'get_config_dict'?
[4200] Failed to execute script 'nodriver_tixcraft' due to unhandled exception!

在无需排队的场次可以正常使用，唯独进入需要排队的场次会出错。

**Comment by max32002** [comment]
update at 2024-04-02,
