### ISSUE TITLE
auto_reload_page_interval 有Bug

### ISSUE THREAD

**Issue by cloudlong1** [max32002/tixcraft_bot#69]
Traceback (most recent call last):
  File "chrome_tixcraft.py", line 10372, in <module>
  File "chrome_tixcraft.py", line 10363, in cli
  File "chrome_tixcraft.py", line 10307, in main
  File "chrome_tixcraft.py", line 8421, in hkticketing_main
TypeError: an integer is required (got type str)
[12696] Failed to execute script 'chrome_tixcraft' due to unhandled exception!

**Comment by max32002** [comment]
fixed at 2023-05-25 version:
https://github.com/max32002/tixcraft_bot/commit/5e43dedeeda39d700840c52810f5a58c770172b6
