### ISSUE TITLE
2023-08-31的version Mac 版本有錯誤

### ISSUE THREAD

**Issue by Leo-Tseng-1992** [max32002/tixcraft_bot#95]
我是用M1版本的Mac，執行settings.py
錯誤訊息：
setting app version: MaxBot (2023.08.31)
python version: 3.11.5
platform: macOS-13.5.1-arm64-arm-64bit
Traceback (most recent call last):
  File "/Users/user/Downloads/MaxBot.app/Contents/Resources/settings.py", line 2612, in <module>
    main()
  File "/Users/user/Downloads/MaxBot.app/Contents/Resources/settings.py", line 2551, in main
    load_GUI(root, config_dict)
  File "/Users/user/Downloads/MaxBot.app/Contents/Resources/settings.py", line 2526, in load_GUI
    PreferenctTab(tab1, config_dict, language_code, UI_PADDING_X)
  File "/Users/user/Downloads/MaxBot.app/Contents/Resources/settings.py", line 1557, in PreferenctTab
    combo_ticket_number.set(str(config_dict["ticket_number"]))
                                ~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'ticket_number'

**Comment by max32002** [comment]
感謝您的回報，請下載前一個版本。

Leo ***@***.***> 於 2023年9月3日 週日 上午1:44 寫道：

**Comment by max32002** [comment]
已重新上傳 2023-08-31-ver-2 版。
